you=input('How are you?')
print(you)
old=input('How old are you?')
print(old)
live=input('Where do you live?')
print(live)
last=input('What is your last name?')
print(last)
first=input('What is your first name?')
print(first)